{% set name = "golines" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/segmentio/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ec1933e0fb73cf0517fd007d325603007aa65ce430267a70fc78cfea43d9716e

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/segmentio/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  dev_url: https://github.com/segmentio/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
